/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_ota                            25
#define gattdb_ota_control                    27
#define gattdb_ThroughputTestService          28
#define gattdb_throughput_indications         30
#define gattdb_throughput_notifications       34
#define gattdb_transmission_on                38
#define gattdb_throughput_result              42
#define gattdb_ThroughputInformationService   45
#define gattdb_connection_phy                 47
#define gattdb_connection_interval            51
#define gattdb_responder_latency              55
#define gattdb_supervision_timeout            59
#define gattdb_pdu_size                       63
#define gattdb_mtu_size                       67


#endif // __GATT_DB_H
